TIME_MAP = {
    "Trading": "📈 Checking Crypto/Stocks",
    "TV Show": "📺 Watching TV",
    "Social Media": "📱 on Social Media",
    "Casual Creative": "🎷 Creative Work",
    "Podcast": "🎧 Listening to Podcast",
    "Music": "🎧 Listening to Music",
    "Sports": "🏀 Playing a Sport",
    "Playing": "🎮 Playing a Game",
    "People": "👱‍♂️ with People",
    "Exploring": "🚶‍♂️ Exploring Somewhere",
    "Chilling": "👱‍♂️ with People",
    "Movie": "🎬 Watching a Movie",
    "Calling": "📞 on the Phone",
    "Messaging": "📱 Responding to Messages",
    "Dating": "👱‍♂️ with People",
    "Private": "🧑‍🦯 In Between Tasks",
    "YouTube": "📺 Watching a Video",
    "News": "📰 Consuming News",
    "Under Influence": "🍺 Having Fun lol",
    "Gaming": "🎮 Playing",
    "Surfing Casually": "🌐 Surfing Mindlessly",
    "Relationship": "👱‍♂️ with People",
    "Washroom": "🚽 in Washroom",
    "Transportation": "🚗 On the Move",
    "Unavoidable Intermission": "👣 On the Move",
    "Driving": "🚗 On the Move",
    "Financial": "💰 Personal Financing",
    "Getting Ready": "👜 Getting Ready",
    "Thinking": "🤔 Thinking",
    "Deciding": "🤔 Making a Decision",
    "Intermission": "👣 On the Move",
    "Location": "👣 On the Move",
    "Listening": "👂 Listening to Something",
    "Hygiene": "🧍 Maintaining Body",
    "Helping Parents": "🤝 Helping",
    "Errands": "🛒 doing Errands",
    "Spiritual": "🧑‍🦯 In Between Tasks",
    "Technicalities": "🧑‍🦯 In Between Tasks",
    "Maintaining": "🔧 Maintaining",
    "Medical": "👨‍⚕️ at Doctor / Dentist",
    "Eating": "🍽️ Eating",
    "Tracking": "⏰ Time Tracking",
    "School": "📚 at School",
    "Food Prep/Clean/Order": "🍽️ Preparing or Ordering Food",
    "Showering": "🧍 Maintaining Body",
    "Unavoidable Family Matters": "👱‍♂️ with People",
    "Sleep": "😴 Sleeping",
    "Shopping": "🛒 Running Errands",
    "Biking": "🛴 On the Move",
    "Analyzing": "🤔 Contemplating",
    "Reflecting": "🤔 Contemplating",
    "Project": "👨‍💻 Working on Startup",
    "Designing": "🎨 Designing",
    "General Learning": "📚 Learning",
    "Yoga": "🧘 doing Yoga",
    "Meditating": "🧘 Meditating",
    "Working Out": "🏋️ Working Out",
    "Planning": "🔮 Planning",
    "Contemplating": "🤔 Contemplating",
    "Skill Learning": "📚 Learning",
    "Studying/Homework": "📚 Learning",
    "Problem Solving": "🧩 Problem Solving",
    "Wycik": "🧑‍🦯 In Between Tasks",
    "Organizing": "🗄️ Organizing",
    "Event": "🎉 at Event",
    "Business": "💼 Doing Business",
    "Book": "📚 Reading",
    "Report": "🖊️ Writing Report",
    "Crypto": "🧑‍🦯 In Between Tasks",
    "Helping/Giving": "🤝 Helping",
    "Meeting": "🤝 Meeting",
    "Researching": "🔍 Researching",
    "Selling": "💰 Selling Something",
    "Practical": "🔥 Doing Something Productive",
    "Concentrating": "🧠 Concentrating",
    "Skill Practicing": "📚 Learning",
    "Formal Learning": "📚 Learning",
    "Recalling": "📚 Learning",
    "Mentoring": "🤝 in a Meeting",
    "Formal Working": "👨‍💻 at Job",
    "Emailing": "📧 Processing Emails",
}

__all__ = ["TIME_MAP"]
